[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "tst-sim-tools"
authors = [
  { name = "Brookhaven National Laboratory", email = "thopkins1@bnl.gov" },
]
description = "Tools for NSLS-II TST beamline's simulated endstation"
readme = "README.md"
license.file = "LICENSE"
requires-python = ">=3.11,<3.14"
classifiers = [
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
]
dynamic = ["version"]
dependencies = [
  "bluesky>=1.15.1",
  "ophyd-async[ca,pva]",
  "blop[cpu,ax,queueserver]",
]

[dependency-groups]
dev = [
  "ophyd-async[ca,sim]",
  "import-linter",
  "numpydoc",
  "pipdeptree",
  "pre-commit",
  "pyright",
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "pytest-mock",
  "ruff",
  "tiled[client,server]>=0.2.14",
  "bluesky-tiled-plugins>=2.0.9",
]
docs = []

[project.urls]
Homepage = "https://github.com/NSLS2/tst-sim-tools"
Issues = "https://github.com/NSLS2/tst-sim-tools/issues"
Discussions = "https://github.com/NSLS2/tst-sim-tools/discussions"
Changelog = "https://github.com/NSLS2/tst-sim-tools/releases"

[tool.hatch]
version.source = "vcs"

[tool.hatch.build]
artifacts = ["src/tst_sim_tools/_version.py"]

[tool.hatch.build.targets.wheel]
sources = ["src"]

[tool.hatch.build.hooks.vcs]
version-file = "src/tst_sim_tools/_version.py"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.pyright]
typeCheckingMode = "standard"

[tool.coverage.paths]
# Tests are run from installed location, map back to the src directory
source = ["src"]

[tool.ruff]
line-length = 125
lint.select = [
  "B",       # flake8-bugbear - https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
  "C4",      # flake8-comprehensions - https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
  "E",       # pycodestyle errors - https://docs.astral.sh/ruff/rules/#error-e
  "F",       # pyflakes rules - https://docs.astral.sh/ruff/rules/#pyflakes-f
  "N",       # pep8-naming - https://docs.astral.sh/ruff/rules/#pep8-naming-n
  "W",       # pycodestyle warnings - https://docs.astral.sh/ruff/rules/#warning-w
  "I",       # isort - https://docs.astral.sh/ruff/rules/#isort-i
  "UP",      # pyupgrade - https://docs.astral.sh/ruff/rules/#pyupgrade-up
  "SLF",     # self - https://docs.astral.sh/ruff/settings/#lintflake8-self
  "PLC2701", # private import - https://docs.astral.sh/ruff/rules/import-private-name/
  "LOG015",  # root logger call - https://docs.astral.sh/ruff/rules/root-logger-call/
  "S101",    # assert - https://docs.astral.sh/ruff/rules/assert/
  "D",       # docstring - https://docs.astral.sh/ruff/rules/#pydocstyle-d
]
lint.ignore = [
  "B901", # Return in a generator is needed for plans
  "D107", # We squash __init__ docstrings into the class docstring
  "D102", # We don't need to override docstrings that are inherited from abstract methods
]
lint.preview = true # so that preview mode PLC2701 is enabled

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
# By default, private member access is allowed in tests
# See https://github.com/DiamondLightSource/python-copier-template/issues/154
# Remove this line to forbid private member access in tests
"tests/**/*" = ["SLF001", "S101", "D"]
"src/tst_sim_tools/startup.py" = [
  "F401",
] # Allow unused imports in startup script


[tool.importlinter]
root_package = "tst_sim_tools"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
tst-sim-tools = { path = ".", editable = true }

[tool.pixi.feature.startup.dependencies]
bluesky-base = ">=1.15"
bluesky-queueserver = "*"
matplotlib-base = ">=3.9.3,<4"
networkx = ">=3.4.2"
nslsii = ">=0.11.4"
numpy = "*"
ophyd = ">=1.11.0"
pyepics = "*"
python = ">=3.12,<3.13"
semver = ">=3.0.4,<4"
tiled-client = ">=0.1.6"
hdf5-external-filter-plugins = ">=0.1.0,<0.2"
blosc-hdf5-plugin = ">=1.0.1,<2"
databroker = "==2.0.0"
epicscorelibs = ">=7.0.7.99.1.1,<8"
bluesky-tiled-plugins = ">=2.0.0"
ophyd-async = ">=0.20.1,<0.21"

[tool.pixi.feature.startup-git.pypi-dependencies]
tst-sim-tools = { git = "https://github.com/NSLS2/tst-sim-tools.git", rev = "main" }

[tool.pixi.feature.startup-local.pypi-dependencies]
tst-sim-tools = { path = ".", editable = true }

[tool.pixi.feature.terminal.dependencies]
ipython = "*"
pyside6 = "*"
numpy = ">2"

[tool.pixi.feature.qs.dependencies]
bluesky-queueserver = "*"
bluesky-httpserver = "*"
bluesky-widgets = ">=0.0.18,<0.0.19"
pyside6 = ">=6.11.1,<7"

[tool.pixi.environments]
default = { solve-group = "default" }
terminal = { features = [
  "terminal",
  "startup",
  "startup-git",
], solve-group = "startup-git", no-default-feature = true }
terminal-local = { features = [
  "terminal",
  "startup",
  "startup-local",
], solve-group = "startup-local", no-default-feature = true }
qs = { features = [
  "qs",
  "startup",
  "startup-git",
], solve-group = "startup-git", no-default-feature = true }
dev = { features = ["dev"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[tool.pixi.feature.startup-local.tasks]
start-local = "TILED=0 ipython -i -m tst_sim_tools.startup"
start-staging = "TILED=1 ipython -i -m tst_sim_tools.startup"
start = "TILED=2 ipython -i -m tst_sim_tools.startup"

[tool.pixi.feature.qs.tasks]
qs-server = """
start-re-manager \
--redis-addr localhost:6379 \
--zmq-control-addr tcp://127.0.0.1:60615 \
--zmq-info-addr tcp://127.0.0.1:60625 \
--zmq-publish-console ON \
--startup-script src/tst_sim_tools/startup.py \
--user-group-permissions /tmp/bsqs \
--existing-plans-devices /tmp/bsqs
"""
http-server = """
QSERVER_ZMQ_CONTROL_ADDRESS=tcp://localhost:60615 \
QSERVER_ZMQ_INFO_ADDRESS=tcp://localhost:60625 \
QSERVER_HTTP_SERVER_SINGLE_USER_API_KEY=secret \
uvicorn --host localhost --port 60610 bluesky_httpserver.server:app
"""
